name: CI/CD
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: unittest
        ports:
          - 3306:3306
        # options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3ntrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.146.0

      - name: Check Ruby version
        run: |
          ruby -v
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --ignore-engines
      - name: Build and run test
        env:
          DB_CONNECTION: mysql
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: ""
          DB_DATABASE: unittest
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler -v 2.3.26
          bundle install --jobs 4 --retry 3
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake db:seed
          bundle exec rspec .
